// Generated by CoffeeScript 1.7.1
(function() {
  var circle, ellipse, ellipseFromBounds, exclusion, intersection, path, pathArrToStr, rect, subtraction, union, _ref;

  _ref = require('./raphael.boolean'), union = _ref.union, subtraction = _ref.subtraction, intersection = _ref.intersection, exclusion = _ref.exclusion, pathArrToStr = _ref.pathArrToStr;

  rect = function(x, y, width, height, r) {
    if (r == null) {
      r = 0;
    }
    return {
      type: 'rect',
      x: x,
      y: y,
      width: width,
      height: height,
      r: r
    };
  };

  path = function(pathStr) {
    return {
      type: 'path',
      path: pathStr
    };
  };

  circle = function(cx, cy, r) {
    return {
      type: 'circle',
      cx: cx,
      cy: cy,
      r: r
    };
  };

  ellipse = function(cx, cy, rx, ry) {
    return {
      type: 'ellipse',
      cx: cx,
      cy: cy,
      rx: rx,
      ry: ry
    };
  };

  ellipseFromBounds = function(x, y, width, height) {
    var cx, cy, rx, ry;
    cx = x + width / 2;
    cy = y + height / 2;
    rx = width / 2;
    ry = height / 2;
    return ellipse(cx, cy, rx, ry);
  };

  module.exports = {
    rect: rect,
    path: path,
    circle: circle,
    ellipse: ellipse,
    ellipseFromBounds: ellipseFromBounds,
    union: union,
    subtraction: subtraction,
    intersection: intersection,
    exclusion: exclusion,
    pathArrToStr: pathArrToStr
  };

}).call(this);
